import { UofReasons } from '../types'

export default {
  SECTION: 'reasonsForUseOfForce',
}

export const QUESTION_SET = {
  REASONS: 'Why was use of force applied against this prisoner?',
  PRIMARY_REASON: 'What was the primary reason use of force was applied against this prisoner?',
}

export const QUESTION_ID = {
  REASONS: 'reasons',
  PRIMARY_REASON: 'primaryReason',
}

export const REASON_DESCRIPTION = {
  ASSAULT_ON_ANOTHER_PRISONER: UofReasons.ASSAULT_ON_ANOTHER_PRISONER.label,
  ASSAULT_ON_A_MEMBER_OF_STAFF: UofReasons.ASSAULT_ON_A_MEMBER_OF_STAFF.label,
  FIGHT_BETWEEN_PRISONERS: UofReasons.FIGHT_BETWEEN_PRISONERS.label,
  TO_PREVENT_HARM_ASSAULT_OR_HARM_TO_OTHERS: UofReasons.TO_PREVENT_HARM_ASSAULT_OR_HARM_TO_OTHERS.label,
  ASSAULT_BY_A_MEMBER_OF_PUBLIC: UofReasons.ASSAULT_BY_A_MEMBER_OF_PUBLIC.label,
  PHYSICAL_THREAT: UofReasons.PHYSICAL_THREAT.label,
  VERBAL_THREAT: UofReasons.VERBAL_THREAT.label,
  REFUSAL_TO_LOCATE_TO_CELL: UofReasons.REFUSAL_TO_LOCATE_TO_CELL.label,
  REFUSAL_TO_TRANSFER: UofReasons.REFUSAL_TO_TRANSFER.label,
  REFUSAL_TO_RELOCATE_CELLS: UofReasons.REFUSAL_TO_RELOCATE_CELLS.label,
  TO_PREVENT_ESCAPE_OR_ABSCONDING: UofReasons.TO_PREVENT_ESCAPE_OR_ABSCONDING.label,
  ATTEMPT_TO_GRAB_STAFF_PPE_OR_EQUIPMENT: UofReasons.ATTEMPT_TO_GRAB_STAFF_PPE_OR_EQUIPMENT.label,
  RISK_REDUCTION_APPLICATION_OF_CUFFS_FOR_ESCORTING: UofReasons.RISK_REDUCTION_APPLICATION_OF_CUFFS_FOR_ESCORTING.label,
  TO_PREVENT_DAMAGE_TO_PROPERTY: UofReasons.TO_PREVENT_DAMAGE_TO_PROPERTY.label,
  SELF_HARM: UofReasons.SELF_HARM.label,
  UNDER_THE_INFLUENCE: UofReasons.UNDER_THE_INFLUENCE.label,
  TO_ADMINISTER_CARE_OR_DUE_TO_THE_MENTAL_CAPACITY_ACT_2005:
    UofReasons.TO_ADMINISTER_CARE_OR_DUE_TO_THE_MENTAL_CAPACITY_ACT_2005.label,
  CONCERTED_INDISCIPLINE: UofReasons.CONCERTED_INDISCIPLINE.label,
  INCIDENT_AT_HEIGHT_NTRG: UofReasons.INCIDENT_AT_HEIGHT_NTRG.label,
  HOSTAGE_NTRG: UofReasons.HOSTAGE_NTRG.label,
  OTHER_NTRG_INCIDENT: UofReasons.OTHER_NTRG_INCIDENT.label,
}
