export default {
  SECTION: 'useOfForceDetails',
}

export const QUESTION_SET = {
  POSITIVE_COMMUNICATION: 'Was positive communication used to de-escalate the situation with this prisoner?',
  BODY_WORN_CAMERA: 'Was any part of the incident captured on a body-worn camera?',
  BODY_WORN_CAMERA_NUMBERS: 'Camera numbers',
  PERSONAL_PROTECTION_TECHNIQUES: 'Were any personal protection techniques used against this prisoner?',
  BATON_DRAWN_AGAINST_PRISONER: 'Was a baton drawn by anyone against this prisoner?',
  BATON_USED: 'Was a baton used against this prisoner?',
  PAVA_DRAWN_AGAINST_PRISONER: 'Was PAVA drawn by anyone against this prisoner?',
  PAVA_USED: 'Was PAVA used against this prisoner?',
  TASER_DRAWN: 'Was a Taser drawn by anyone against this prisoner?',
  TASER_OPERATIVE_PRESENT: 'Was the prisoner warned that a Taser operative was present?',
  RED_DOT_WARNING: 'Was a red-dot warning used?',
  ARC_WARNING_USED: 'Was an arc warning used?',
  TASER_DEPLOYED: 'Was the Taser deployed?',
  TASER_CYCLE_EXTENDED: 'Was the Taser cycle extended?',
  TASER_REENERGISED: 'Was the Taser re-energised?',
  BITTEN_BY_PRISON_DOG: 'Was the prisoner bitten by a prison dog?',
  WEAPONS_OBSERVED: 'Were any weapons observed?',
  WEAPON_TYPES: 'Weapon type',
  GUIDING_HOLD: 'Was a guiding hold used against this prisoner?',
  GUIDING_HOLD_OFFICERS_INVOLVED: 'How many officers were involved?',
  ESCORTING_HOLD: 'Was an escorting hold used against this prisoner?',
  RESTRAINT_POSITIONS: 'Which control and restraint positions were used against this prisoner?',
  PAIN_INDUCING_TECHNIQUES_USED: 'Which pain inducing techniques were used against this prisoner?',
  HANDCUFFS_APPLIED: 'Were handcuffs applied against this prisoner?',
}

export const QUESTION_ID = {
  POSITIVE_COMMUNICATION: 'positiveCommunication',
  BODY_WORN_CAMERAS: 'bodyWornCamera',
  BODY_WORN_CAMERA_NUMBERS: 'bodyWornCameraNumbers',
  PERSONAL_PROTECTION_TECHNIQUES: 'personalProtectionTechniques',
  BATON_DRAWN_AGAINST_PRISONER: 'batonDrawnAgainstPrisoner',
  BATON_USED: 'batonUsed',
  PAVA_DRAWN_AGAINST_PRISONER: 'pavaDrawnAgainstPrisoner',
  PAVA_USED: 'pavaUsed',
  TASER_DRAWN: 'taserDrawn',
  TASER_OPERATIVE_PRESENT: 'taserOperativePresent',
  RED_DOT_WARNING: 'redDotWarning',
  ARC_WARNING_USED: 'arcWarningUsed',
  TASER_DEPLOYED: 'taserDeployed',
  TASER_CYCLE_EXTENDED: 'taserCycleExtended',
  TASER_REENERGISED: 'taserReenergised',
  BITTEN_BY_PRISON_DOG: 'bittenByPrisonDog',
  WEAPONS_OBSERVED: 'weaponsObserved',
  WEAPON_TYPES: 'weaponTypes',
  GUIDING_HOLD: 'guidingHold',
  GUIDING_HOLD_OFFICERS_INVOLVED: 'guidingHoldOfficersInvolved',
  ESCORTING_HOLD: 'escortingHold',
  RESTRAINT_POSITIONS: 'restraintPositions',
  PAIN_INDUCING_TECHNIQUES_USED: 'painInducingTechniquesUsed',
  HANDCUFFS_APPLIED: 'handcuffsApplied',
}
