---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: use-of-force
  alertSeverity: digital-prison-service-dev

generic-data-analytics-extractor:
  databaseSecretName: dps-rds-instance-output
  destinationS3SecretName: uof-analytical-platform-reporting-s3-bucket
  enabled: true
  serviceAccountName: use-of-force-dev-to-ap-s3

ingress:
  v1_2_enabled: true
