---
# Values here are the same across all environments
generic-service:
  nameOverride: use-of-force
  replicaCount: 4

  image:
    repository: quay.io/hmpps/use-of-force
    tag: latest
    port: 3000

  ingress:
    enabled: true
    tlsSecretName: use-of-force-cert
    path: /
  
  livenessProbe:
    httpGet:
      path: /health

  readinessProbe:
    httpGet:
      path: /health

  env:
    TOKENVERIFICATION_API_ENABLED: true
    FEATURE_FLAG_OUTAGE_BANNER_ENABLED: false
    FEATURE_FLAG_REMOVE_CELL_LOCATION_AGENCIES: 'HMI'
    DB_SSL_ENABLED: true
    REDIS_TLS_ENABLED: true
    NODE_ENV: production
    PRODUCT_ID: 'DPS045'

  namespace_secrets:
    dps-rds-instance-output:
      DB_PASS: database_password
      DB_USER: database_username
      DB_SERVER: rds_instance_address
      DB_NAME: database_name
      DB_HOST: url
    use-of-force:
      API_CLIENT_ID: API_CLIENT_ID
      API_CLIENT_SECRET: API_CLIENT_SECRET
      SYSTEM_CLIENT_ID: SYSTEM_CLIENT_ID
      SYSTEM_CLIENT_SECRET: SYSTEM_CLIENT_SECRET
      APPINSIGHTS_INSTRUMENTATIONKEY: APPINSIGHTS_INSTRUMENTATIONKEY
      NOTIFY_API_KEY: NOTIFY_API_KEY
      TAG_MANAGER_KEY: TAG_MANAGER_KEY
      TAG_MANAGER_ENVIRONMENT: TAG_MANAGER_ENVIRONMENT
      SESSION_SECRET: SESSION_SECRET
      URL_SIGNING_SECRET: URL_SIGNING_SECRET
    uof-elasticache-redis:
      REDIS_HOST: primary_endpoint_address
      REDIS_AUTH_TOKEN: auth_token

  allowlist:
    groups:
      - moj_cloud_platform
      - digital_staff_and_mojo

generic-prometheus-alerts:
  targetApplication: use-of-force
  alertSeverity: move-a-prisoner-alerts-nonprod

generic-data-analytics-extractor:
  databaseSecretName: dps-rds-instance-output
  destinationS3SecretName: uof-analytical-platform-reporting-s3-bucket
  enabled: true
  serviceAccountName: use-of-force-dev-to-ap-s3
  dataPlatformApiAuthSecretName: use-of-force-api-auth
  dataProductName: hmpps_use_of_force
