module.exports = {
  offender: {
    bookingId: 1001,
    offenderNo: 'A1234AC',
    firstName: 'NORMAN',
    lastName: 'SMITH',
    agencyId: 'MDI',
    prisonName: 'IT Prison',
    cellLocation: 'TST-01-01',
    dateOfBirth: '2000-12-26',
    status: 'ACTIVE IN',
  },
  offender2: {
    bookingId: 1002,
    offenderNo: 'A1234AD',
    firstName: 'JUNE',
    lastName: 'JONES',
    agencyId: 'MDI',
    cellLocation: 'TST-01-02',
    prisonName: 'IT Prison',
    dateOfBirth: '2000-12-26',
  },
  offender3: {
    bookingId: 1003,
    offenderNo: 'A1234AE',
    firstName: 'SIMON',
    lastName: 'SMITH',
    agencyId: 'MDI',
    cellLocation: 'TST-01-03',
    prisonName: 'IT Prison',
    dateOfBirth: '2000-12-26',
  },
}
