apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-reminders
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: use-of-force
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
            args:
            - node
            - job/sendReminders
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
          successfulJobsHistoryLimit: 5
          failedJobsHistoryLimit: 3
          concurrencyPolicy: Forbid
        