apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-reminders
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: use-of-force
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
            args:
            - node
            - job/send-reminders
          restartPolicy: Never