apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    prometheus: cloud-platform
spec:
  groups:
  - name: use-of-force
    rules:
    - alert: KubeCronJobRunning
      annotations:
        message: CronJob {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.cronjob {{ "}}" }} was scheduled to start over 10 minutes ago
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecronjobrunning
      expr: time() - kube_cronjob_next_schedule_time{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"} > 600
      for: 10m
      labels:
        severity: digital-prison-service
    - alert: KubeJobCompletion
      annotations:
        message: CronJob {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.job_name {{ "}}" }} failed.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion
      expr: |-
        kube_job_spec_completions{job="kube-state-metrics"} - kube_job_status_succeeded{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"} > 0
      for: 10m
      labels:
        severity: digital-prison-service
